#! /bin/bash
### BEGIN INIT INFO
# Provides:          Wheel of fortune
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run //home/pi/wof/wof if it exist
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin


do_start() {
	log="/home/pi/wof/wof_log"
	c=1

	while [ -f "$log$c" ]
	do
		(( c++ ))
	done
	
	if [ -x /home/pi/wof/wof ]; then
	        [ "$VERBOSE" != no ] && log_begin_msg "Running Wheel of Fortune"
		/home/pi/wof/wof -L $log$c
		ES=$?
		[ "$VERBOSE" != no ] && log_end_msg $ES
		return $ES
	fi
}

case "$1" in
    start)
	do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop|status)
        # No-op
        exit 0
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
